INSERT INTO `category` 
VALUES 
  (1, 'Beverages', ''), 
  (2, 'Seafood', ''), 
  (3, 'Office supplies', ''), 
  (4, 'Themed meals', ''), 
  (5, 'Other stuff', ''), 
  (6, 'Baby stuff', ''), 
  (7, 'Snacks', ''), 
  (8, 'Dairy', ''), 
  (9, 'Fresh fruits', ''), 
  (10, 'Cleaning products', ''), 
  (11, 'Personal care', ''), 
  (12, 'Fresh vegetables', ''), 
  (13, 'Medicine', ''), 
  (14, 'Refrigerated items', ''), 
  (15, 'Meat', ''), 
  (16, 'Frozen', ''), 
  (17, 'Baking', ''), 
  (18, 'Kitchen', ''), 
  (19, 'Cheese', ''), 
  (20, 'Spices & herbs', ''), 
  (21, 'Canned foods', ''), 
  (22, 'Pets', ''), 
  (23, 'Carcinogens', ''), 
  (24, 'Condiments / Sauces', ''), 
  (25, 'Various groceries', ''), 
  (26, 'Baked goods', '');
